//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adora_Apparel1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="stock_purchasing", Namespace="http://schemas.datacontract.org/2004/07/DataModel")]
    [System.SerializableAttribute()]
    public partial class stock_purchasing : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> ActualCostPerPieceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> MiscellanouseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NoOfPeicesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> PricePerPieceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Shippment_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> Supplier_CommisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> Total_Shippment_costField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> Transport_CostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idStock_purchasingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> shipped_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Adora_Apparel1.ServiceReference1.shippment_title shippment_titleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> statusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> ActualCostPerPiece {
            get {
                return this.ActualCostPerPieceField;
            }
            set {
                if ((this.ActualCostPerPieceField.Equals(value) != true)) {
                    this.ActualCostPerPieceField = value;
                    this.RaisePropertyChanged("ActualCostPerPiece");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Miscellanouse {
            get {
                return this.MiscellanouseField;
            }
            set {
                if ((this.MiscellanouseField.Equals(value) != true)) {
                    this.MiscellanouseField = value;
                    this.RaisePropertyChanged("Miscellanouse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NoOfPeices {
            get {
                return this.NoOfPeicesField;
            }
            set {
                if ((this.NoOfPeicesField.Equals(value) != true)) {
                    this.NoOfPeicesField = value;
                    this.RaisePropertyChanged("NoOfPeices");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> PricePerPiece {
            get {
                return this.PricePerPieceField;
            }
            set {
                if ((this.PricePerPieceField.Equals(value) != true)) {
                    this.PricePerPieceField = value;
                    this.RaisePropertyChanged("PricePerPiece");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Shippment_code {
            get {
                return this.Shippment_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.Shippment_codeField, value) != true)) {
                    this.Shippment_codeField = value;
                    this.RaisePropertyChanged("Shippment_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Supplier_Commision {
            get {
                return this.Supplier_CommisionField;
            }
            set {
                if ((this.Supplier_CommisionField.Equals(value) != true)) {
                    this.Supplier_CommisionField = value;
                    this.RaisePropertyChanged("Supplier_Commision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Total_Shippment_cost {
            get {
                return this.Total_Shippment_costField;
            }
            set {
                if ((this.Total_Shippment_costField.Equals(value) != true)) {
                    this.Total_Shippment_costField = value;
                    this.RaisePropertyChanged("Total_Shippment_cost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Transport_Cost {
            get {
                return this.Transport_CostField;
            }
            set {
                if ((this.Transport_CostField.Equals(value) != true)) {
                    this.Transport_CostField = value;
                    this.RaisePropertyChanged("Transport_Cost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idStock_purchasing {
            get {
                return this.idStock_purchasingField;
            }
            set {
                if ((this.idStock_purchasingField.Equals(value) != true)) {
                    this.idStock_purchasingField = value;
                    this.RaisePropertyChanged("idStock_purchasing");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> shipped_date {
            get {
                return this.shipped_dateField;
            }
            set {
                if ((this.shipped_dateField.Equals(value) != true)) {
                    this.shipped_dateField = value;
                    this.RaisePropertyChanged("shipped_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Adora_Apparel1.ServiceReference1.shippment_title shippment_title {
            get {
                return this.shippment_titleField;
            }
            set {
                if ((object.ReferenceEquals(this.shippment_titleField, value) != true)) {
                    this.shippment_titleField = value;
                    this.RaisePropertyChanged("shippment_title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="shippment_title", Namespace="http://schemas.datacontract.org/2004/07/DataModel")]
    [System.SerializableAttribute()]
    public partial class shippment_title : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Shipment_CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Shippment_title1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Adora_Apparel1.ServiceReference1.fob_purchasing[] fob_purchasingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Adora_Apparel1.ServiceReference1.fob_sales[] fob_salesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Adora_Apparel1.ServiceReference1.fob_stock_in_hand[] fob_stock_in_handField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Adora_Apparel1.ServiceReference1.fob_stock_orders[] fob_stock_ordersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> isFOBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Adora_Apparel1.ServiceReference1.stock_monitor[] stock_monitorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Adora_Apparel1.ServiceReference1.stock_purchasing[] stock_purchasingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Adora_Apparel1.ServiceReference1.stock_sales[] stock_salesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Adora_Apparel1.ServiceReference1.stock[] stocksField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Shipment_Code {
            get {
                return this.Shipment_CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.Shipment_CodeField, value) != true)) {
                    this.Shipment_CodeField = value;
                    this.RaisePropertyChanged("Shipment_Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Shippment_title1 {
            get {
                return this.Shippment_title1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Shippment_title1Field, value) != true)) {
                    this.Shippment_title1Field = value;
                    this.RaisePropertyChanged("Shippment_title1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Adora_Apparel1.ServiceReference1.fob_purchasing[] fob_purchasing {
            get {
                return this.fob_purchasingField;
            }
            set {
                if ((object.ReferenceEquals(this.fob_purchasingField, value) != true)) {
                    this.fob_purchasingField = value;
                    this.RaisePropertyChanged("fob_purchasing");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Adora_Apparel1.ServiceReference1.fob_sales[] fob_sales {
            get {
                return this.fob_salesField;
            }
            set {
                if ((object.ReferenceEquals(this.fob_salesField, value) != true)) {
                    this.fob_salesField = value;
                    this.RaisePropertyChanged("fob_sales");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Adora_Apparel1.ServiceReference1.fob_stock_in_hand[] fob_stock_in_hand {
            get {
                return this.fob_stock_in_handField;
            }
            set {
                if ((object.ReferenceEquals(this.fob_stock_in_handField, value) != true)) {
                    this.fob_stock_in_handField = value;
                    this.RaisePropertyChanged("fob_stock_in_hand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Adora_Apparel1.ServiceReference1.fob_stock_orders[] fob_stock_orders {
            get {
                return this.fob_stock_ordersField;
            }
            set {
                if ((object.ReferenceEquals(this.fob_stock_ordersField, value) != true)) {
                    this.fob_stock_ordersField = value;
                    this.RaisePropertyChanged("fob_stock_orders");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> isFOB {
            get {
                return this.isFOBField;
            }
            set {
                if ((this.isFOBField.Equals(value) != true)) {
                    this.isFOBField = value;
                    this.RaisePropertyChanged("isFOB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Adora_Apparel1.ServiceReference1.stock_monitor[] stock_monitor {
            get {
                return this.stock_monitorField;
            }
            set {
                if ((object.ReferenceEquals(this.stock_monitorField, value) != true)) {
                    this.stock_monitorField = value;
                    this.RaisePropertyChanged("stock_monitor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Adora_Apparel1.ServiceReference1.stock_purchasing[] stock_purchasing {
            get {
                return this.stock_purchasingField;
            }
            set {
                if ((object.ReferenceEquals(this.stock_purchasingField, value) != true)) {
                    this.stock_purchasingField = value;
                    this.RaisePropertyChanged("stock_purchasing");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Adora_Apparel1.ServiceReference1.stock_sales[] stock_sales {
            get {
                return this.stock_salesField;
            }
            set {
                if ((object.ReferenceEquals(this.stock_salesField, value) != true)) {
                    this.stock_salesField = value;
                    this.RaisePropertyChanged("stock_sales");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Adora_Apparel1.ServiceReference1.stock[] stocks {
            get {
                return this.stocksField;
            }
            set {
                if ((object.ReferenceEquals(this.stocksField, value) != true)) {
                    this.stocksField = value;
                    this.RaisePropertyChanged("stocks");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="fob_purchasing", Namespace="http://schemas.datacontract.org/2004/07/DataModel")]
    [System.SerializableAttribute()]
    public partial class fob_purchasing : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Shipment_CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> costField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> cost_per_yardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idFOB_PurchasingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> price_per_yardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Adora_Apparel1.ServiceReference1.shippment_title shippment_titleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> transport_costField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> yardageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Shipment_Code {
            get {
                return this.Shipment_CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.Shipment_CodeField, value) != true)) {
                    this.Shipment_CodeField = value;
                    this.RaisePropertyChanged("Shipment_Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> cost {
            get {
                return this.costField;
            }
            set {
                if ((this.costField.Equals(value) != true)) {
                    this.costField = value;
                    this.RaisePropertyChanged("cost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> cost_per_yard {
            get {
                return this.cost_per_yardField;
            }
            set {
                if ((this.cost_per_yardField.Equals(value) != true)) {
                    this.cost_per_yardField = value;
                    this.RaisePropertyChanged("cost_per_yard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idFOB_Purchasing {
            get {
                return this.idFOB_PurchasingField;
            }
            set {
                if ((this.idFOB_PurchasingField.Equals(value) != true)) {
                    this.idFOB_PurchasingField = value;
                    this.RaisePropertyChanged("idFOB_Purchasing");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> price_per_yard {
            get {
                return this.price_per_yardField;
            }
            set {
                if ((this.price_per_yardField.Equals(value) != true)) {
                    this.price_per_yardField = value;
                    this.RaisePropertyChanged("price_per_yard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Adora_Apparel1.ServiceReference1.shippment_title shippment_title {
            get {
                return this.shippment_titleField;
            }
            set {
                if ((object.ReferenceEquals(this.shippment_titleField, value) != true)) {
                    this.shippment_titleField = value;
                    this.RaisePropertyChanged("shippment_title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> transport_cost {
            get {
                return this.transport_costField;
            }
            set {
                if ((this.transport_costField.Equals(value) != true)) {
                    this.transport_costField = value;
                    this.RaisePropertyChanged("transport_cost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> yardage {
            get {
                return this.yardageField;
            }
            set {
                if ((this.yardageField.Equals(value) != true)) {
                    this.yardageField = value;
                    this.RaisePropertyChanged("yardage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="fob_sales", Namespace="http://schemas.datacontract.org/2004/07/DataModel")]
    [System.SerializableAttribute()]
    public partial class fob_sales : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> NoOfPeicesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> PricePerPeiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SellingFrequencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Shippment_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> TotalPeicesSoldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> TotalRemainingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> TotalTurnOversField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idFOB_SalesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Adora_Apparel1.ServiceReference1.shippment_title shippment_titleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> NoOfPeices {
            get {
                return this.NoOfPeicesField;
            }
            set {
                if ((this.NoOfPeicesField.Equals(value) != true)) {
                    this.NoOfPeicesField = value;
                    this.RaisePropertyChanged("NoOfPeices");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> PricePerPeice {
            get {
                return this.PricePerPeiceField;
            }
            set {
                if ((this.PricePerPeiceField.Equals(value) != true)) {
                    this.PricePerPeiceField = value;
                    this.RaisePropertyChanged("PricePerPeice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SellingFrequency {
            get {
                return this.SellingFrequencyField;
            }
            set {
                if ((this.SellingFrequencyField.Equals(value) != true)) {
                    this.SellingFrequencyField = value;
                    this.RaisePropertyChanged("SellingFrequency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Shippment_code {
            get {
                return this.Shippment_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.Shippment_codeField, value) != true)) {
                    this.Shippment_codeField = value;
                    this.RaisePropertyChanged("Shippment_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> TotalPeicesSold {
            get {
                return this.TotalPeicesSoldField;
            }
            set {
                if ((this.TotalPeicesSoldField.Equals(value) != true)) {
                    this.TotalPeicesSoldField = value;
                    this.RaisePropertyChanged("TotalPeicesSold");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> TotalRemaining {
            get {
                return this.TotalRemainingField;
            }
            set {
                if ((this.TotalRemainingField.Equals(value) != true)) {
                    this.TotalRemainingField = value;
                    this.RaisePropertyChanged("TotalRemaining");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> TotalTurnOvers {
            get {
                return this.TotalTurnOversField;
            }
            set {
                if ((this.TotalTurnOversField.Equals(value) != true)) {
                    this.TotalTurnOversField = value;
                    this.RaisePropertyChanged("TotalTurnOvers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idFOB_Sales {
            get {
                return this.idFOB_SalesField;
            }
            set {
                if ((this.idFOB_SalesField.Equals(value) != true)) {
                    this.idFOB_SalesField = value;
                    this.RaisePropertyChanged("idFOB_Sales");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Adora_Apparel1.ServiceReference1.shippment_title shippment_title {
            get {
                return this.shippment_titleField;
            }
            set {
                if ((object.ReferenceEquals(this.shippment_titleField, value) != true)) {
                    this.shippment_titleField = value;
                    this.RaisePropertyChanged("shippment_title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="fob_stock_in_hand", Namespace="http://schemas.datacontract.org/2004/07/DataModel")]
    [System.SerializableAttribute()]
    public partial class fob_stock_in_hand : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Shippment_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double amountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> price_per_peiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Adora_Apparel1.ServiceReference1.shippment_title shippment_titleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Shippment_code {
            get {
                return this.Shippment_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.Shippment_codeField, value) != true)) {
                    this.Shippment_codeField = value;
                    this.RaisePropertyChanged("Shippment_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double amount {
            get {
                return this.amountField;
            }
            set {
                if ((this.amountField.Equals(value) != true)) {
                    this.amountField = value;
                    this.RaisePropertyChanged("amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> price_per_peice {
            get {
                return this.price_per_peiceField;
            }
            set {
                if ((this.price_per_peiceField.Equals(value) != true)) {
                    this.price_per_peiceField = value;
                    this.RaisePropertyChanged("price_per_peice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Adora_Apparel1.ServiceReference1.shippment_title shippment_title {
            get {
                return this.shippment_titleField;
            }
            set {
                if ((object.ReferenceEquals(this.shippment_titleField, value) != true)) {
                    this.shippment_titleField = value;
                    this.RaisePropertyChanged("shippment_title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="fob_stock_orders", Namespace="http://schemas.datacontract.org/2004/07/DataModel")]
    [System.SerializableAttribute()]
    public partial class fob_stock_orders : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> CostPerPeiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Factory_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> NoOfPeicesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Shippment_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idFOB_StockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> materialAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Adora_Apparel1.ServiceReference1.shippment_title shippment_titleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Adora_Apparel1.ServiceReference1.user userField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string user_usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> CostPerPeice {
            get {
                return this.CostPerPeiceField;
            }
            set {
                if ((this.CostPerPeiceField.Equals(value) != true)) {
                    this.CostPerPeiceField = value;
                    this.RaisePropertyChanged("CostPerPeice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Factory_Name {
            get {
                return this.Factory_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Factory_NameField, value) != true)) {
                    this.Factory_NameField = value;
                    this.RaisePropertyChanged("Factory_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Item {
            get {
                return this.ItemField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemField, value) != true)) {
                    this.ItemField = value;
                    this.RaisePropertyChanged("Item");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> NoOfPeices {
            get {
                return this.NoOfPeicesField;
            }
            set {
                if ((this.NoOfPeicesField.Equals(value) != true)) {
                    this.NoOfPeicesField = value;
                    this.RaisePropertyChanged("NoOfPeices");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Shippment_code {
            get {
                return this.Shippment_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.Shippment_codeField, value) != true)) {
                    this.Shippment_codeField = value;
                    this.RaisePropertyChanged("Shippment_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idFOB_Stock {
            get {
                return this.idFOB_StockField;
            }
            set {
                if ((this.idFOB_StockField.Equals(value) != true)) {
                    this.idFOB_StockField = value;
                    this.RaisePropertyChanged("idFOB_Stock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> materialAmount {
            get {
                return this.materialAmountField;
            }
            set {
                if ((this.materialAmountField.Equals(value) != true)) {
                    this.materialAmountField = value;
                    this.RaisePropertyChanged("materialAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Adora_Apparel1.ServiceReference1.shippment_title shippment_title {
            get {
                return this.shippment_titleField;
            }
            set {
                if ((object.ReferenceEquals(this.shippment_titleField, value) != true)) {
                    this.shippment_titleField = value;
                    this.RaisePropertyChanged("shippment_title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Adora_Apparel1.ServiceReference1.user user {
            get {
                return this.userField;
            }
            set {
                if ((object.ReferenceEquals(this.userField, value) != true)) {
                    this.userField = value;
                    this.RaisePropertyChanged("user");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string user_username {
            get {
                return this.user_usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.user_usernameField, value) != true)) {
                    this.user_usernameField = value;
                    this.RaisePropertyChanged("user_username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="stock_monitor", Namespace="http://schemas.datacontract.org/2004/07/DataModel")]
    [System.SerializableAttribute()]
    public partial class stock_monitor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Shipment_CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> amountBeforeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> amountNowField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> dateModifieddField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string reasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string responsibleUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Adora_Apparel1.ServiceReference1.shippment_title shippment_titleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Adora_Apparel1.ServiceReference1.user userField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userModifiedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Shipment_Code {
            get {
                return this.Shipment_CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.Shipment_CodeField, value) != true)) {
                    this.Shipment_CodeField = value;
                    this.RaisePropertyChanged("Shipment_Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> amountBefore {
            get {
                return this.amountBeforeField;
            }
            set {
                if ((this.amountBeforeField.Equals(value) != true)) {
                    this.amountBeforeField = value;
                    this.RaisePropertyChanged("amountBefore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> amountNow {
            get {
                return this.amountNowField;
            }
            set {
                if ((this.amountNowField.Equals(value) != true)) {
                    this.amountNowField = value;
                    this.RaisePropertyChanged("amountNow");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> dateModifiedd {
            get {
                return this.dateModifieddField;
            }
            set {
                if ((this.dateModifieddField.Equals(value) != true)) {
                    this.dateModifieddField = value;
                    this.RaisePropertyChanged("dateModifiedd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string reason {
            get {
                return this.reasonField;
            }
            set {
                if ((object.ReferenceEquals(this.reasonField, value) != true)) {
                    this.reasonField = value;
                    this.RaisePropertyChanged("reason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string responsibleUser {
            get {
                return this.responsibleUserField;
            }
            set {
                if ((object.ReferenceEquals(this.responsibleUserField, value) != true)) {
                    this.responsibleUserField = value;
                    this.RaisePropertyChanged("responsibleUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Adora_Apparel1.ServiceReference1.shippment_title shippment_title {
            get {
                return this.shippment_titleField;
            }
            set {
                if ((object.ReferenceEquals(this.shippment_titleField, value) != true)) {
                    this.shippment_titleField = value;
                    this.RaisePropertyChanged("shippment_title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Adora_Apparel1.ServiceReference1.user user {
            get {
                return this.userField;
            }
            set {
                if ((object.ReferenceEquals(this.userField, value) != true)) {
                    this.userField = value;
                    this.RaisePropertyChanged("user");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userModified {
            get {
                return this.userModifiedField;
            }
            set {
                if ((object.ReferenceEquals(this.userModifiedField, value) != true)) {
                    this.userModifiedField = value;
                    this.RaisePropertyChanged("userModified");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="stock_sales", Namespace="http://schemas.datacontract.org/2004/07/DataModel")]
    [System.SerializableAttribute()]
    public partial class stock_sales : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NoOfPeicesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> PricePerPeiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Selling_FrequencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Shippment_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Total_RemainingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> Total_TurnoverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Total_peices_soldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idStock_SalesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Adora_Apparel1.ServiceReference1.shippment_title shippment_titleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NoOfPeices {
            get {
                return this.NoOfPeicesField;
            }
            set {
                if ((this.NoOfPeicesField.Equals(value) != true)) {
                    this.NoOfPeicesField = value;
                    this.RaisePropertyChanged("NoOfPeices");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> PricePerPeice {
            get {
                return this.PricePerPeiceField;
            }
            set {
                if ((this.PricePerPeiceField.Equals(value) != true)) {
                    this.PricePerPeiceField = value;
                    this.RaisePropertyChanged("PricePerPeice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Selling_Frequency {
            get {
                return this.Selling_FrequencyField;
            }
            set {
                if ((this.Selling_FrequencyField.Equals(value) != true)) {
                    this.Selling_FrequencyField = value;
                    this.RaisePropertyChanged("Selling_Frequency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Shippment_code {
            get {
                return this.Shippment_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.Shippment_codeField, value) != true)) {
                    this.Shippment_codeField = value;
                    this.RaisePropertyChanged("Shippment_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Total_Remaining {
            get {
                return this.Total_RemainingField;
            }
            set {
                if ((this.Total_RemainingField.Equals(value) != true)) {
                    this.Total_RemainingField = value;
                    this.RaisePropertyChanged("Total_Remaining");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Total_Turnover {
            get {
                return this.Total_TurnoverField;
            }
            set {
                if ((this.Total_TurnoverField.Equals(value) != true)) {
                    this.Total_TurnoverField = value;
                    this.RaisePropertyChanged("Total_Turnover");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Total_peices_sold {
            get {
                return this.Total_peices_soldField;
            }
            set {
                if ((this.Total_peices_soldField.Equals(value) != true)) {
                    this.Total_peices_soldField = value;
                    this.RaisePropertyChanged("Total_peices_sold");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idStock_Sales {
            get {
                return this.idStock_SalesField;
            }
            set {
                if ((this.idStock_SalesField.Equals(value) != true)) {
                    this.idStock_SalesField = value;
                    this.RaisePropertyChanged("idStock_Sales");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Adora_Apparel1.ServiceReference1.shippment_title shippment_title {
            get {
                return this.shippment_titleField;
            }
            set {
                if ((object.ReferenceEquals(this.shippment_titleField, value) != true)) {
                    this.shippment_titleField = value;
                    this.RaisePropertyChanged("shippment_title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="stock", Namespace="http://schemas.datacontract.org/2004/07/DataModel")]
    [System.SerializableAttribute()]
    public partial class stock : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Shippment_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> price_per_peiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Adora_Apparel1.ServiceReference1.shippment_title shippment_titleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> stockInHandField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Shippment_code {
            get {
                return this.Shippment_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.Shippment_codeField, value) != true)) {
                    this.Shippment_codeField = value;
                    this.RaisePropertyChanged("Shippment_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> price_per_peice {
            get {
                return this.price_per_peiceField;
            }
            set {
                if ((this.price_per_peiceField.Equals(value) != true)) {
                    this.price_per_peiceField = value;
                    this.RaisePropertyChanged("price_per_peice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Adora_Apparel1.ServiceReference1.shippment_title shippment_title {
            get {
                return this.shippment_titleField;
            }
            set {
                if ((object.ReferenceEquals(this.shippment_titleField, value) != true)) {
                    this.shippment_titleField = value;
                    this.RaisePropertyChanged("shippment_title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> stockInHand {
            get {
                return this.stockInHandField;
            }
            set {
                if ((this.stockInHandField.Equals(value) != true)) {
                    this.stockInHandField = value;
                    this.RaisePropertyChanged("stockInHand");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="user", Namespace="http://schemas.datacontract.org/2004/07/DataModel")]
    [System.SerializableAttribute()]
    public partial class user : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnswerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Adora_Apparel1.ServiceReference1.fixed_over_heads[] fixed_over_headsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Adora_Apparel1.ServiceReference1.fob_stock_orders[] fob_stock_ordersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string securityQuestionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Adora_Apparel1.ServiceReference1.stock_monitor[] stock_monitorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Answer {
            get {
                return this.AnswerField;
            }
            set {
                if ((object.ReferenceEquals(this.AnswerField, value) != true)) {
                    this.AnswerField = value;
                    this.RaisePropertyChanged("Answer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameField, value) != true)) {
                    this.firstNameField = value;
                    this.RaisePropertyChanged("firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Adora_Apparel1.ServiceReference1.fixed_over_heads[] fixed_over_heads {
            get {
                return this.fixed_over_headsField;
            }
            set {
                if ((object.ReferenceEquals(this.fixed_over_headsField, value) != true)) {
                    this.fixed_over_headsField = value;
                    this.RaisePropertyChanged("fixed_over_heads");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Adora_Apparel1.ServiceReference1.fob_stock_orders[] fob_stock_orders {
            get {
                return this.fob_stock_ordersField;
            }
            set {
                if ((object.ReferenceEquals(this.fob_stock_ordersField, value) != true)) {
                    this.fob_stock_ordersField = value;
                    this.RaisePropertyChanged("fob_stock_orders");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastNameField, value) != true)) {
                    this.lastNameField = value;
                    this.RaisePropertyChanged("lastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string securityQuestion {
            get {
                return this.securityQuestionField;
            }
            set {
                if ((object.ReferenceEquals(this.securityQuestionField, value) != true)) {
                    this.securityQuestionField = value;
                    this.RaisePropertyChanged("securityQuestion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Adora_Apparel1.ServiceReference1.stock_monitor[] stock_monitor {
            get {
                return this.stock_monitorField;
            }
            set {
                if ((object.ReferenceEquals(this.stock_monitorField, value) != true)) {
                    this.stock_monitorField = value;
                    this.RaisePropertyChanged("stock_monitor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="fixed_over_heads", Namespace="http://schemas.datacontract.org/2004/07/DataModel")]
    [System.SerializableAttribute()]
    public partial class fixed_over_heads : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> Date_FromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> Date_ToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Type_Of_CostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> amountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string enteredByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Adora_Apparel1.ServiceReference1.user userField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Date_From {
            get {
                return this.Date_FromField;
            }
            set {
                if ((this.Date_FromField.Equals(value) != true)) {
                    this.Date_FromField = value;
                    this.RaisePropertyChanged("Date_From");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Date_To {
            get {
                return this.Date_ToField;
            }
            set {
                if ((this.Date_ToField.Equals(value) != true)) {
                    this.Date_ToField = value;
                    this.RaisePropertyChanged("Date_To");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type_Of_Cost {
            get {
                return this.Type_Of_CostField;
            }
            set {
                if ((object.ReferenceEquals(this.Type_Of_CostField, value) != true)) {
                    this.Type_Of_CostField = value;
                    this.RaisePropertyChanged("Type_Of_Cost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> amount {
            get {
                return this.amountField;
            }
            set {
                if ((this.amountField.Equals(value) != true)) {
                    this.amountField = value;
                    this.RaisePropertyChanged("amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string enteredBy {
            get {
                return this.enteredByField;
            }
            set {
                if ((object.ReferenceEquals(this.enteredByField, value) != true)) {
                    this.enteredByField = value;
                    this.RaisePropertyChanged("enteredBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Adora_Apparel1.ServiceReference1.user user {
            get {
                return this.userField;
            }
            set {
                if ((object.ReferenceEquals(this.userField, value) != true)) {
                    this.userField = value;
                    this.RaisePropertyChanged("user");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getstockPurchasing", ReplyAction="http://tempuri.org/IService1/getstockPurchasingResponse")]
        Adora_Apparel1.ServiceReference1.stock_purchasing[] getstockPurchasing();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getstockPurchasing", ReplyAction="http://tempuri.org/IService1/getstockPurchasingResponse")]
        System.Threading.Tasks.Task<Adora_Apparel1.ServiceReference1.stock_purchasing[]> getstockPurchasingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addStockPurchase", ReplyAction="http://tempuri.org/IService1/addStockPurchaseResponse")]
        bool addStockPurchase(string ship_code, System.Nullable<int> peices, System.Nullable<double> peice_price, System.Nullable<double> transport_cost, System.Nullable<double> supplier_commision, System.Nullable<double> miscellenaouse, System.Nullable<double> total_ship_cost, System.Nullable<double> actual_cost, int status, System.Nullable<System.DateTime> shipped);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addStockPurchase", ReplyAction="http://tempuri.org/IService1/addStockPurchaseResponse")]
        System.Threading.Tasks.Task<bool> addStockPurchaseAsync(string ship_code, System.Nullable<int> peices, System.Nullable<double> peice_price, System.Nullable<double> transport_cost, System.Nullable<double> supplier_commision, System.Nullable<double> miscellenaouse, System.Nullable<double> total_ship_cost, System.Nullable<double> actual_cost, int status, System.Nullable<System.DateTime> shipped);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addUser", ReplyAction="http://tempuri.org/IService1/addUserResponse")]
        bool addUser(string username, string firstname, string lastname, string password, string security, string answer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addUser", ReplyAction="http://tempuri.org/IService1/addUserResponse")]
        System.Threading.Tasks.Task<bool> addUserAsync(string username, string firstname, string lastname, string password, string security, string answer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/login", ReplyAction="http://tempuri.org/IService1/loginResponse")]
        bool login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/login", ReplyAction="http://tempuri.org/IService1/loginResponse")]
        System.Threading.Tasks.Task<bool> loginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updateStockPurchase", ReplyAction="http://tempuri.org/IService1/updateStockPurchaseResponse")]
        bool updateStockPurchase(string ship_code, System.Nullable<int> peices, System.Nullable<double> peice_price, System.Nullable<double> transport_cost, System.Nullable<double> supplier_commision, System.Nullable<double> miscellenaouse, System.Nullable<double> total_ship_cost, System.Nullable<double> actual_cost, int shipID, System.Nullable<System.DateTime> shipped);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updateStockPurchase", ReplyAction="http://tempuri.org/IService1/updateStockPurchaseResponse")]
        System.Threading.Tasks.Task<bool> updateStockPurchaseAsync(string ship_code, System.Nullable<int> peices, System.Nullable<double> peice_price, System.Nullable<double> transport_cost, System.Nullable<double> supplier_commision, System.Nullable<double> miscellenaouse, System.Nullable<double> total_ship_cost, System.Nullable<double> actual_cost, int shipID, System.Nullable<System.DateTime> shipped);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteStockPurchase", ReplyAction="http://tempuri.org/IService1/deleteStockPurchaseResponse")]
        bool deleteStockPurchase(int ship_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteStockPurchase", ReplyAction="http://tempuri.org/IService1/deleteStockPurchaseResponse")]
        System.Threading.Tasks.Task<bool> deleteStockPurchaseAsync(int ship_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addNewShipment", ReplyAction="http://tempuri.org/IService1/addNewShipmentResponse")]
        bool addNewShipment(string shippment_code, string shipment_title, System.Nullable<bool> status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addNewShipment", ReplyAction="http://tempuri.org/IService1/addNewShipmentResponse")]
        System.Threading.Tasks.Task<bool> addNewShipmentAsync(string shippment_code, string shipment_title, System.Nullable<bool> status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getshippmentTitle", ReplyAction="http://tempuri.org/IService1/getshippmentTitleResponse")]
        string[] getshippmentTitle();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getshippmentTitle", ReplyAction="http://tempuri.org/IService1/getshippmentTitleResponse")]
        System.Threading.Tasks.Task<string[]> getshippmentTitleAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Adora_Apparel1.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Adora_Apparel1.ServiceReference1.IService1>, Adora_Apparel1.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Adora_Apparel1.ServiceReference1.stock_purchasing[] getstockPurchasing() {
            return base.Channel.getstockPurchasing();
        }
        
        public System.Threading.Tasks.Task<Adora_Apparel1.ServiceReference1.stock_purchasing[]> getstockPurchasingAsync() {
            return base.Channel.getstockPurchasingAsync();
        }
        
        public bool addStockPurchase(string ship_code, System.Nullable<int> peices, System.Nullable<double> peice_price, System.Nullable<double> transport_cost, System.Nullable<double> supplier_commision, System.Nullable<double> miscellenaouse, System.Nullable<double> total_ship_cost, System.Nullable<double> actual_cost, int status, System.Nullable<System.DateTime> shipped) {
            return base.Channel.addStockPurchase(ship_code, peices, peice_price, transport_cost, supplier_commision, miscellenaouse, total_ship_cost, actual_cost, status, shipped);
        }
        
        public System.Threading.Tasks.Task<bool> addStockPurchaseAsync(string ship_code, System.Nullable<int> peices, System.Nullable<double> peice_price, System.Nullable<double> transport_cost, System.Nullable<double> supplier_commision, System.Nullable<double> miscellenaouse, System.Nullable<double> total_ship_cost, System.Nullable<double> actual_cost, int status, System.Nullable<System.DateTime> shipped) {
            return base.Channel.addStockPurchaseAsync(ship_code, peices, peice_price, transport_cost, supplier_commision, miscellenaouse, total_ship_cost, actual_cost, status, shipped);
        }
        
        public bool addUser(string username, string firstname, string lastname, string password, string security, string answer) {
            return base.Channel.addUser(username, firstname, lastname, password, security, answer);
        }
        
        public System.Threading.Tasks.Task<bool> addUserAsync(string username, string firstname, string lastname, string password, string security, string answer) {
            return base.Channel.addUserAsync(username, firstname, lastname, password, security, answer);
        }
        
        public bool login(string username, string password) {
            return base.Channel.login(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> loginAsync(string username, string password) {
            return base.Channel.loginAsync(username, password);
        }
        
        public bool updateStockPurchase(string ship_code, System.Nullable<int> peices, System.Nullable<double> peice_price, System.Nullable<double> transport_cost, System.Nullable<double> supplier_commision, System.Nullable<double> miscellenaouse, System.Nullable<double> total_ship_cost, System.Nullable<double> actual_cost, int shipID, System.Nullable<System.DateTime> shipped) {
            return base.Channel.updateStockPurchase(ship_code, peices, peice_price, transport_cost, supplier_commision, miscellenaouse, total_ship_cost, actual_cost, shipID, shipped);
        }
        
        public System.Threading.Tasks.Task<bool> updateStockPurchaseAsync(string ship_code, System.Nullable<int> peices, System.Nullable<double> peice_price, System.Nullable<double> transport_cost, System.Nullable<double> supplier_commision, System.Nullable<double> miscellenaouse, System.Nullable<double> total_ship_cost, System.Nullable<double> actual_cost, int shipID, System.Nullable<System.DateTime> shipped) {
            return base.Channel.updateStockPurchaseAsync(ship_code, peices, peice_price, transport_cost, supplier_commision, miscellenaouse, total_ship_cost, actual_cost, shipID, shipped);
        }
        
        public bool deleteStockPurchase(int ship_code) {
            return base.Channel.deleteStockPurchase(ship_code);
        }
        
        public System.Threading.Tasks.Task<bool> deleteStockPurchaseAsync(int ship_code) {
            return base.Channel.deleteStockPurchaseAsync(ship_code);
        }
        
        public bool addNewShipment(string shippment_code, string shipment_title, System.Nullable<bool> status) {
            return base.Channel.addNewShipment(shippment_code, shipment_title, status);
        }
        
        public System.Threading.Tasks.Task<bool> addNewShipmentAsync(string shippment_code, string shipment_title, System.Nullable<bool> status) {
            return base.Channel.addNewShipmentAsync(shippment_code, shipment_title, status);
        }
        
        public string[] getshippmentTitle() {
            return base.Channel.getshippmentTitle();
        }
        
        public System.Threading.Tasks.Task<string[]> getshippmentTitleAsync() {
            return base.Channel.getshippmentTitleAsync();
        }
    }
}
