//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mydbEntities : DbContext
    {
        public mydbEntities()
            : base("name=mydbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<fixed_over_heads> fixed_over_heads { get; set; }
        public DbSet<fob_purchasing> fob_purchasing { get; set; }
        public DbSet<fob_sales> fob_sales { get; set; }
        public DbSet<fob_stock_in_hand> fob_stock_in_hand { get; set; }
        public DbSet<fob_stock_orders> fob_stock_orders { get; set; }
        public DbSet<shippment_title> shippment_title { get; set; }
        public DbSet<stock> stocks { get; set; }
        public DbSet<stock_monitor> stock_monitor { get; set; }
        public DbSet<stock_purchasing> stock_purchasing { get; set; }
        public DbSet<stock_sales> stock_sales { get; set; }
        public DbSet<user> users { get; set; }
    }
}
