//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock
    {
        public int id { get; set; }
        public string Shippment_code { get; set; }
        public Nullable<double> stockInHand { get; set; }
        public Nullable<double> price_per_peice { get; set; }
    
        public virtual shippment_title shippment_title { get; set; }
    }
}
