//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.fixed_over_heads = new HashSet<fixed_over_heads>();
            this.fob_stock_orders = new HashSet<fob_stock_orders>();
            this.stock_monitor = new HashSet<stock_monitor>();
        }
    
        public string username { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string password { get; set; }
        public string securityQuestion { get; set; }
        public string Answer { get; set; }
    
        public virtual ICollection<fixed_over_heads> fixed_over_heads { get; set; }
        public virtual ICollection<fob_stock_orders> fob_stock_orders { get; set; }
        public virtual ICollection<stock_monitor> stock_monitor { get; set; }
    }
}
