//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock_purchasing
    {
        public int idStock_purchasing { get; set; }
        public string Shippment_code { get; set; }
        public Nullable<int> NoOfPeices { get; set; }
        public Nullable<double> PricePerPiece { get; set; }
        public Nullable<double> Transport_Cost { get; set; }
        public Nullable<double> Supplier_Commision { get; set; }
        public string Miscellanouse { get; set; }
        public Nullable<double> Total_Shippment_cost { get; set; }
        public Nullable<double> ActualCostPerPiece { get; set; }

        public int status { get; set; }
    
        public virtual shippment_title shippment_title { get; set; }
    }
}
